# Generated by Django 5.0.4 on 2024-04-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('schedule_interval', models.CharField(help_text='E.g @daily', max_length=50)),
                ('default_args', models.JSONField(default=dict)),
                ('start_date', models.DateTimeField()),
                ('paused', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DAGRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RUNNING', 'RUNNING')], max_length=20)),
                ('dag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dag_app.dag')),
            ],
        ),
    ]
